#!/usr/bin/env bash
export PROJECT_ID='evekhm-testlab'
export PROJECT_NAME='Test Lab'

export FOLDER=261046259366
export BILLING='01382E-07CCE9-615E10'

export VM='test-vm'
export EMAIL='evekhm@google.com'

export REGION='us-west1'
export ZONE='us-west1-a'


#gcloud projects add-iam-policy-binding $PROJECT_ID \
#    --member=user:$EMAIL \
#    --role=roles/iap.tunnelResourceAccessor
#gcloud projects add-iam-policy-binding $PROJECT_ID \
#    --member=user:$EMAIL \
#    --role=roles/compute.instanceAdmin.v1
#gcloud projects add-iam-policy-binding $PROJECT_ID \
#    --member=user:$EMAIL \
#    --role=roles/iam.serviceAccountUser
